apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vs-code
spec:
  tls: # https = http + tls -> couche de confidentialité, client et serveur ne parlent pas en clair mais definissent un tunnel de confidentialité dans lequel ils sont les seuls à comprendre le contenu
    - hosts:
        - vscode_clem.kub.sspcloud.fr
  rules:
  - host: vscode_clem.kub.sspcloud.fr

    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: # c'est bien le nom du service
            name: vs-code
            port: 
              number: 6901



