apiVersion: v1
kind: Service
metadata:
  name:  vs-code   #nom du service unique (trio)
spec:
  selector:
    app: vs-code # c'est bien le label mis au pod qui est recherché local à un namespace
  ports:
    - protocol: TCP
      port: 6901 # port du service
      targetPort:  6901  # port standard


       